# Generated by Django 5.2.8 on 2025-11-22 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=datetime.date.today)),
                ('desc', models.TextField(help_text='Enter comment about the blog here', max_length=200)),
            ],
        ),
    ]
