# Generated by Django 5.2.8 on 2025-11-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_desc_comment_description_comment_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(help_text='Enter comment about the blog here', max_length=75),
        ),
    ]
